# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  shoulder_pan_joint:
    has_position_limits: True  # Modified
    max_position: 3.14 # Modified
    min_position: -3.14 # Modified
    has_velocity_limits: true
    max_velocity: 2.5
    has_acceleration_limits: true
    max_acceleration: 1.5
  shoulder_lift_joint:
    has_position_limits: True  # Modified
    max_position: 3.14 # Modified
    min_position: -3.14 # Modified
    has_velocity_limits: true
    max_velocity: 2.5
    has_acceleration_limits: true
    max_acceleration: 1.5
  elbow_joint:
    has_position_limits: True  # Modified
    max_position: 3.14  # Modified
    min_position: 0.0 # Modified
    has_velocity_limits: true
    max_velocity: 2.5
    has_acceleration_limits: true
    max_acceleration: 1.5
  wrist_1_joint:
    has_position_limits: True  # Modified
    max_position: 0.0 # Modified
    min_position: -3.14 # Modified
    has_velocity_limits: true
    max_velocity: 2.5
    has_acceleration_limits: true
    max_acceleration: 1.5
  wrist_2_joint:
    has_position_limits: True  # Modified
    max_position: -3.14/4 # Modified
    min_position: -3*3.14/4 # Modified
    has_velocity_limits: true
    max_velocity: 2.5
    has_acceleration_limits: true
    max_acceleration: 1.5
  wrist_3_joint:
    has_position_limits: True  # Modified
    max_position:  3.14 # Modified
    min_position: -3.14 # Modified
    has_velocity_limits: true
    max_velocity: 2.5
    has_acceleration_limits: true
    max_acceleration: 3.0
